"""Frozen internal governance contracts for the v0.5-D3.2 assumption registry."""

from csd_foundry.governance.v0_5._assumption_governance_contracts import (
    ASSUMPTION_AUTHORITY_ACTIONS,
    ASSUMPTION_EVALUATION_PHASES,
    ASSUMPTION_EVALUATION_WORK_SCHEMA_VERSION,
    ASSUMPTION_GOVERNANCE_ROLES,
    ASSUMPTION_MATERIALITIES,
    AUTHORITY_GRANT_SCHEMA_VERSION,
    AUTHORITY_POLICY_COMMIT_SCHEMA_VERSION,
    AUTHORITY_POLICY_SCHEMA_VERSION,
    DECISION_ASSUMPTION_BINDING_SCHEMA_VERSION,
    DUTY_EXCEPTION_SCHEMA_VERSION,
    GLOBAL_ASSUMPTION_SCOPE,
    GOVERNANCE_ROLE_FACT_SCHEMA_VERSION,
    POLICY_APPROVAL_CLASSES,
    RESOLUTION_AUTHORITY_ACTIONS,
    RESOLUTION_AUTHORITY_BINDING_SCHEMA_VERSION,
    SEPARATION_DUTY_RULE_SCHEMA_VERSION,
    AssumptionAuthorityGrant,
    AssumptionAuthorityPolicy,
    AssumptionAuthorityPolicyCommit,
    AssumptionDutyException,
    AssumptionEvaluationWork,
    AssumptionGovernanceContractError,
    AssumptionResolutionAuthorityBinding,
    AssumptionSeparationDutyRule,
    DecisionAssumptionBinding,
    canonical_cycle_witness,
)
from csd_foundry.governance.v0_5._assumption_governance_role_derivation import (
    AssumptionGovernanceRoleFact,
    derive_assumption_governance_role,
    derive_prior_governance_roles,
)

__all__ = [
    "ASSUMPTION_AUTHORITY_ACTIONS",
    "ASSUMPTION_EVALUATION_PHASES",
    "ASSUMPTION_EVALUATION_WORK_SCHEMA_VERSION",
    "ASSUMPTION_GOVERNANCE_ROLES",
    "ASSUMPTION_MATERIALITIES",
    "AUTHORITY_GRANT_SCHEMA_VERSION",
    "AUTHORITY_POLICY_COMMIT_SCHEMA_VERSION",
    "AUTHORITY_POLICY_SCHEMA_VERSION",
    "DECISION_ASSUMPTION_BINDING_SCHEMA_VERSION",
    "DUTY_EXCEPTION_SCHEMA_VERSION",
    "GLOBAL_ASSUMPTION_SCOPE",
    "GOVERNANCE_ROLE_FACT_SCHEMA_VERSION",
    "POLICY_APPROVAL_CLASSES",
    "RESOLUTION_AUTHORITY_ACTIONS",
    "RESOLUTION_AUTHORITY_BINDING_SCHEMA_VERSION",
    "SEPARATION_DUTY_RULE_SCHEMA_VERSION",
    "AssumptionAuthorityGrant",
    "AssumptionAuthorityPolicy",
    "AssumptionAuthorityPolicyCommit",
    "AssumptionDutyException",
    "AssumptionEvaluationWork",
    "AssumptionGovernanceContractError",
    "AssumptionGovernanceRoleFact",
    "AssumptionResolutionAuthorityBinding",
    "AssumptionSeparationDutyRule",
    "DecisionAssumptionBinding",
    "canonical_cycle_witness",
    "derive_assumption_governance_role",
    "derive_prior_governance_roles",
]
