"""Correct escaped source literals in the issue #23 one-shot generator."""

from pathlib import Path

path = Path(__file__).with_name("apply_issue_23_shards.py")
text = path.read_text(encoding="utf-8")
old = r'corrupt_path.write_bytes(b"corrupt\n")'
new = r'corrupt_path.write_bytes(b"corrupt\\n")'
if old not in text:
    raise RuntimeError("expected generated bytes literal was not found")
path.write_text(text.replace(old, new, 1), encoding="utf-8")
