"""Packaged manifest metadata for the immutable CSD Reasoning Seed v0.1 release."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class ManifestScenario:
    scenario_id: str
    split: str
    family: str
    source_section: str
    rules: frozenset[str]


def _entry(
    scenario_id: str,
    split: str,
    family: str,
    source_section: str,
    *rules: str,
) -> ManifestScenario:
    return ManifestScenario(
        scenario_id=scenario_id,
        split=split,
        family=family,
        source_section=source_section,
        rules=frozenset(rules),
    )


SCENARIO_METADATA: tuple[ManifestScenario, ...] = (
    _entry(
        "M-01",
        "train",
        "revocation_non_inference",
        "Charter §12 M-01",
        "INV-11",
        "INV-12",
        "INV-13",
        "INV-15",
        "SYM-01",
    ),
    _entry(
        "M-02",
        "train",
        "lost_source_basis",
        "Charter §12 M-02",
        "INV-05",
        "INV-11",
        "INV-13",
        "INV-15",
    ),
    _entry(
        "M-03",
        "train",
        "expiry_and_staleness",
        "Charter §12 M-03",
        "INV-06",
        "INV-07",
        "INV-09",
        "INV-15",
        "INV-20",
        "INV-21",
    ),
    _entry(
        "M-04",
        "train",
        "independent_failure_preservation",
        "Charter §12 M-04",
        "INV-11",
        "INV-14",
        "INV-16",
        "INV-21",
        "SYM-01",
    ),
    _entry(
        "M-05",
        "train",
        "unsupported_historical_verdict",
        "Charter §12 M-05",
        "INV-07",
        "INV-09",
        "INV-13",
        "INV-15",
    ),
    _entry(
        "M-06",
        "train",
        "alternative_basis",
        "Charter §12 M-06",
        "INV-11",
        "INV-14",
        "INV-16",
    ),
    _entry(
        "M-07",
        "train",
        "no_replacement_verdict",
        "Charter §12 M-07",
        "INV-09",
        "INV-12",
        "INV-13",
        "INV-15",
    ),
    _entry(
        "M-08",
        "train",
        "level_preserving_recovery",
        "Charter §12 M-08",
        "INV-17",
        "INV-18",
        "G-INV-10",
    ),
    _entry(
        "M-09",
        "train",
        "governed_source_restoration",
        "Charter §12 M-09",
        "INV-05",
        "INV-18",
        "G-INV-09",
        "G-INV-10",
    ),
    _entry(
        "M-10",
        "train",
        "dependency_scoped_multi_control",
        "Charter §12 M-10 and README Layer 2",
        "INV-11",
        "INV-14",
        "INV-15",
        "INV-16",
    ),
    _entry(
        "M-11",
        "train",
        "atomic_interleavings",
        "Charter §12 M-11 and README Layer 2",
        "INV-03",
        "INV-07",
        "INV-18",
        "INV-19",
        "INV-20",
    ),
    _entry(
        "G-01",
        "train",
        "evidence_is_not_verdict",
        "README Layer 3B workflow 1",
        "INV-07",
        "G-INV-07",
        "A-07",
    ),
    _entry(
        "G-02",
        "train",
        "new_identity_restoration",
        "README Layer 3B workflow 2",
        "INV-18",
        "G-INV-06",
        "G-INV-08",
        "G-INV-09",
        "G-INV-10",
        "G-INV-11",
    ),
    _entry(
        "C-01",
        "train",
        "fresh_adverse_evidence",
        "Charter §7.2 and INV-21",
        "INV-07",
        "INV-21",
    ),
    _entry(
        "M-12",
        "validation",
        "age_trigger_symmetry",
        "Charter §12 M-12",
        "INV-11",
        "INV-14",
        "INV-15",
        "INV-20",
        "INV-21",
    ),
    _entry(
        "M-13",
        "validation",
        "non_current_obligation",
        "Charter §12 M-13",
        "INV-04",
        "INV-12",
    ),
    _entry(
        "M-14",
        "validation",
        "profile_strengthening",
        "Charter §12 M-14 and README Layer 3B workflow 3",
        "INV-08",
        "INV-09",
        "G-INV-12",
        "G-INV-14",
    ),
    _entry(
        "G-04",
        "validation",
        "governed_retirement",
        "README Layer 3B workflow 4",
        "INV-04",
        "INV-19",
        "G-INV-11",
        "G-INV-12",
        "G-INV-13",
    ),
    _entry(
        "M-15",
        "test",
        "assumption_boundary",
        "Charter §12 M-15 and Layer 3A results",
        "A-04",
        "INV-11",
        "REAL-01",
        "REAL-02",
    ),
    _entry(
        "L-01",
        "test",
        "conditional_liveness",
        "Charter LIVE-01 and README temporal structure",
        "LIVE-01",
        "INV-07",
        "INV-18",
        "INV-19",
    ),
    _entry(
        "H-01",
        "test",
        "append_only_history",
        "Charter INV-19 and counterexample policy",
        "INV-18",
        "INV-19",
        "G-INV-06",
        "G-INV-11",
    ),
)

if len(SCENARIO_METADATA) != 21:
    raise RuntimeError(f"expected 21 manifest scenarios, found {len(SCENARIO_METADATA)}")
