"""Contract layer for the CSD Foundry v0.4 synthesis engine."""

from csd_foundry.synthesis.v0_4.contracts import (
    CompletenessEvidenceKind,
    CompletenessWitnessMap,
    ConstraintProof,
    CoverageTarget,
    EligibilityProof,
    EscapeClassification,
    EscapeSeverity,
    GenerationAttempt,
    HoldoutRule,
    InfeasibilityProofMethod,
    InfeasibilityWitness,
    MutationRiskBudget,
    MutationRiskPolicy,
    RejectionCause,
    RejectionOwner,
    ReleasePolicy,
    SearchBudget,
    SemanticEffect,
    TargetDisposition,
    TrajectoryPlan,
)
from csd_foundry.synthesis.v0_4.validation import validate_release

__all__ = [
    "CompletenessEvidenceKind",
    "CompletenessWitnessMap",
    "ConstraintProof",
    "CoverageTarget",
    "EligibilityProof",
    "EscapeClassification",
    "EscapeSeverity",
    "GenerationAttempt",
    "HoldoutRule",
    "InfeasibilityProofMethod",
    "InfeasibilityWitness",
    "MutationRiskBudget",
    "MutationRiskPolicy",
    "RejectionCause",
    "RejectionOwner",
    "ReleasePolicy",
    "SearchBudget",
    "SemanticEffect",
    "TargetDisposition",
    "TrajectoryPlan",
    "validate_release",
]
